### ISSUE TITLE
Uncaught Error: ENOENT, keymaps/darwin.json not found in /Applications/Atom.app/Contents/Resources/app.asar

### ISSUE THREAD

**Issue by dkarter** [atom/keybinding-resolver#20] opened 2015-04-27 03:43 UTC
1. (CMD+S) save file with the keybinding resolver open
2. click the link to `Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js`

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [keybinding-resolver](https://github.com/atom/keybinding-resolver) package, v0.31.0

### Stack Trace

Uncaught Error: ENOENT, keymaps/darwin.json not found in /Applications/Atom.app/Contents/Resources/app.asar

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:457

Error: ENOENT, keymaps/darwin.json not found in /Applications/Atom.app/Contents/Resources/app.asar
  at createNotFoundError (ATOM_SHELL_ASAR.js:101:13)
  at Object.module.(anonymous function) [as open] (ATOM_SHELL_ASAR.js:156:25)
  at ReadStream.open (fs.js:1668:6)
  at new ReadStream (fs.js:1655:10)
  at Object.fs.createReadStream (fs.js:1610:10)
  at File.module.exports.File.read (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:286:27)
  at TextBuffer.module.exports.TextBuffer.updateCachedDiskContents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:948:61)
  at TextBuffer.module.exports.TextBuffer.load (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:974:19)
  at Project.module.exports.Project.buildBuffer (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:446:21)
  at Project.module.exports.Project.bufferForPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:416:63)
  at Project.module.exports.Project.open (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:379:19)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:439:31)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:365:19)
  at HTMLTableCellElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/keybinding-resolver/lib/keybinding-resolver-view.js:41:31)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
  2x -0:57.7.0 key-binding-resolver:toggle (div.settings-view.pane-item)
     -0:55.5.0 settings-view:open (div.settings-view.pane-item)
     -0:54.9.0 core:close (div.settings-view.pane-item)
     -0:53.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:51.9.0 core:close (div.settings-view.pane-item)
     -0:51.3.0 key-binding-resolver:toggle (atom-text-editor.editor.is-focused)
     -0:48.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:47.9.0 core:move-down (atom-text-editor.editor.is-focused)
 12x -0:47.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:44.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:27.2.0 core:confirm (atom-text-editor.editor.mini)
     -0:27.2.0 pretty-json:prettify (atom-text-editor.editor.is-focused)
     -0:15.4.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:14 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tabs",
      "tree-view",
      "file-icon-supplement"
    ],
    "themes": [
      "isotope-ui",
      "monokai-low-profile-syntax"
    ],
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
ScssBundle, v0.4.0
angularjs, v0.1.0
atom-beautify, v0.24.1
atom-color-highlight, v3.0.9
atom-spotify, v1.2.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
autocomplete-ruby, v0.1.0
autocomplete-snippets, v1.2.0
color-picker, v1.7.0
coverage, v0.5.1
emmet, v2.3.8
file-icons, v1.5.4
gist-it, v0.6.10
git-blame, v0.4.0
git-tab-status, v1.7.0
isotope-ui, v2.1.2
javascript-snippets, v1.0.0
jsformat, v0.8.0
language-haml, v0.20.0
language-rspec, v0.3.0
linter, v0.12.1
linter-erb, v0.1.0
linter-haml, v0.1.1
linter-jshint, v0.1.2
linter-rubocop, v0.2.3
linter-ruby, v0.1.4
linter-scss-lint, v0.0.14
live-archive, v0.1.13
minimap, v4.7.6
monokai-low-profile-syntax, v0.1.1
pain-split, v1.3.1
pretty-json, v0.3.3
quick-move-file, v0.7.0
rspec-snippets, v0.4.0
ruby-bundler, v0.2.1
ruby-test, v0.9.6
sublime-tabs, v0.5.6
trailing-spaces, v0.2.5
travis-ci-status, v0.13.0
yuno-commit, v0.0.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment] 2015-04-27 11:45
Duplicate of atom/atom#6511 which will be fixed in the next Atom version, 0.195.0.

**Closed by 50Wliu** 2015-04-27 11:45 UTC
