### ISSUE TITLE
Suggestion: Needs a close button

### ISSUE THREAD

**Issue by proehlen** [atom/keybinding-resolver#40] opened 2016-07-21 10:35 UTC
I never use this tool, accidentally opened it and then spent five minutes google-searching how to close the thing (unsuccessfully). I tried shutting down atom and restarting and it was still there.  A little close button might be useful and less time-wasting for anyone affected since Cmd-. isn't exactly obvious and contradicts some google results.

**Comment by thomasjo** [comment] 2016-07-21 11:20
Duplicate of #17.

**Closed by thomasjo** 2016-07-21 11:20 UTC
