### ISSUE TITLE
wrong key showed

### ISSUE THREAD

**Issue by schlichtanders** [atom/keybinding-resolver#36] opened 2016-02-07 18:49 UTC
Dear all,
I just started with atom and want to make it my default editor, now I already run into weird issues: My key-strokes are interpreted differently by the keybinding-resolver (wrong keys) compared to the atom-texteditor (correct keys). This is already not intented I think, but furthermore, I fear that also the keybindings themselves get messed up.

I have a german keyboard layout.

For instance, the "and"-symbol `&` is well printed in the editor, while keybinding-resolver shows `^`.
Another more regular error occurs if I type `[` (which is altgr-8) - I get a `8` in the keybinding-resolver (same for all other altgr combinations).

Does anyone know why this happens, whether this is harmful and if, how I can resolve it correctly?

Hoping for your help,
best,
Stephan

**Comment by lee-dohm** [comment] 2016-02-08 17:00
This is a duplicate of https://github.com/atom/atom-keymap/issues/35. Please subscribe there for updates.

**Closed by lee-dohm** 2016-02-08 17:00 UTC

**Comment by schlichtanders** [comment] 2016-02-08 19:50
Thank you very much for forwarding me there.
I found the "Keyboard localization package" mentioned there, which in fact
fixes almost everything. Only ^ ° ´ ` seem missing, but for now I can live
without them I think.

thanks again!
