### ISSUE TITLE
Does not resolve cmd-: (cmd-shift-;) on OS X with Brazilian ABNT2 keyboard

### ISSUE THREAD

**Issue by UltCombo** [atom/keybinding-resolver#28] opened 2015-07-29 20:14 UTC
Using OS X 10.10.4, when I switch the keyboard layout to Brazilian ABNT2, Atom no longer resolves `cmd-:` (`cmd-shift-;`).

It is as if it wouldn't detect the `:` keypress when I'm holding `cmd` and `shift`, but the `:` works otherwise. Here's a video demonstrating the issue: https://youtu.be/rxvlTSJ7jd8

**Comment by mnquintana** [comment] 2015-07-29 20:50
This looks like a duplicate of https://github.com/atom/atom-keymap/issues/37 – please subscribe there for updates.

**Closed by mnquintana** 2015-07-29 20:50 UTC

**Comment by UltCombo** [comment] 2015-07-29 22:20
Thanks for the quick reply. :smiley:
I'll investigate the issue further after reading the linked thread.

Though, it strikes me as odd as it seems the key is not captured at all, instead of being mis-mapped. The keyboard-localization package fails to capture it as well, so it might be a problem in the Atom core.

This very same binding works fine in Sublime Text.

**Comment by UltCombo** [comment] 2015-08-03 01:21
FWIW, I've worked around the issue by remapping the key combination to an unused key (e.g. F19) using [Karabiner](https://github.com/tekezo/Karabiner), then I've bound this remapped key to the command I wanted in Atom.

My Karabiner's `private.xml`:

```xml
<?xml version="1.0"?>
<root>
	<appdef>
		<appname>ATOM</appname>
		<equal>com.github.atom</equal>
	</appdef>

	<item>
		<name>Command+shift+; to F19</name>
		<identifier>private.command_shift_semicolon_to_F19</identifier>
		<only>ATOM</only>
		<autogen>__KeyToKey__ KeyCode::SLASH, ModifierFlag::COMMAND_L, ModifierFlag::SHIFT_L, KeyCode::F19</autogen>
		<autogen>__KeyToKey__ KeyCode::SLASH, ModifierFlag::COMMAND_R, ModifierFlag::SHIFT_R, KeyCode::F19</autogen>
	</item>
</root>
```
