### ISSUE TITLE
Needs a visual way to close it.

### ISSUE THREAD

**Issue by akhayat** [atom/keybinding-resolver#17] opened 2015-03-26 00:50 UTC
I accidentally opened this thing, had no idea what it was, and no idea how to close it. I had to google "atom keybinding resolver" to find this page. It needs an 'X' button somewhere.

**Comment by bronson** [comment] 2015-05-19 21:13
I agree, absolutely, but the core team might not: https://github.com/atom/find-and-replace/issues/164#issuecomment-44226984

**Comment by bronson** [comment] 2015-05-19 21:20
Heck, we need a consistent way to close it.  Cmd-period toggles this pane and Esc does nothing.  However, Cmd-F shows the Find Pane and requires Esc to close it.

Little inconsistencies add up.

**Comment by thomasjo** [comment] 2015-05-19 21:24
<kbd>Escape</kbd> closes the keybinding resolver as expected here. Got any packages installed that's interfering perhaps? See if you can reproduce the behavior in safe mode; `atom --safe`.

**Comment by bronson** [comment] 2015-05-19 21:34
Ah, yep.  It's vim-mode.  But somehow the Find pane works and this one doesn't.

**Comment by bronson** [comment] 2015-05-19 21:39
In https://github.com/atom/find-and-replace/issues/164#issuecomment-44226984 the Find authors say that the keypress should not toggle the pane.  Not sure if I agree with that, but it does seem like the two panes should behave the same way.

**Comment by thomasjo** [comment] 2015-05-19 21:40
Probably because the find pane gets focus, whereas the keybinding resolver pane doesn't. The keybinding resolves is created in such a way as to not grab focus to interfere with any keybindings bound to the editor, tree view and what not.

Just a guess, but if you open the find pane, click (or otherwise send focus to) an editor, then try to press <kbd>Escape</kdb>, `vim-mode` will interfere in a similar fashion.

**Comment by thomasjo** [comment] 2015-05-19 21:41
> but it does seem like the two panes should behave the same way

They do behave the same way. Your problem is, as you discovered, caused by the `vim-mode` package.

**Comment by bronson** [comment] 2015-05-19 21:49
Problems are easy, what's the solution?  Have the keybinding-resolver work around it?  File a bug on vim-mode?  Don't use vim-mode?

**Comment by bronson** [comment] 2015-05-19 21:50
> They do behave the same way

I don't think so...?  Cmd-. toggles the pane, Cmd-F doesn't.

**Comment by thomasjo** [comment] 2015-05-19 21:55
> I don't think so...? Cmd-. toggles the pane, Cmd-F doesn't.

Good point, although I thought you were referring to the escape behavior. But again, the keybinding resolver does not work the same as the find pane. One gets focus, the other one doesn't. I'm not sure it's a good idea to compare them since they are quite different.

With regards to a fix, I think we might have to investigate some form of special behavior when `vim-mode` is enabled.

**Comment by Donalmartin** [comment] 2015-09-08 15:06
CTRL-Windows Key - period for those not on a mac

**Closed** 2019-04-04 19:37 UTC
Labels: enhancement
