### ISSUE TITLE
is this a joke or what?

### ISSUE THREAD

**Issue by cryptid11** [atom/keybinding-resolver#39] opened 2016-03-13 04:08 UTC
it complitely miss the keyboard, probably using us one, but this is really horrible, how it's possible a program to write doesn't even understand my keyboard? I think it can be worst than this...

**Comment by 50Wliu** [comment] 2016-03-13 16:13
This is most likely a duplicate of atom/atom-keymap#37 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-03-13 16:13 UTC
